### ISSUE TITLE
Wrong function call

### ISSUE THREAD

**Issue by naory159** [lukhnos/LuceneSearchDemo-Android#2]
in app/src/main/java/org/lukhnos/lucenesearchdemo/DetailActivity.java,
It's need to be:
`intent.putExtra(DetailActivity.EXTRA_REVIEW, result.searchResult.getHighlightedReview(result.doc));`

(`getHighlightedReview`, not `getFullHighlightedReview`, Line 227)

**Comment by lukhnos** [comment]
This is intended. `getHighlightedReview()` gets you a highlighted snippet to be used in the result list view, whereas `getFullHighlightedReview` gets you the highlighted *full text*, which we want in `DetailActivity`.

**Comment by naory159** [comment]
But there is no such function at all!!
There is no function called `getFullHighlightedReview`

**Comment by lukhnos** [comment]
It's from the [SearchResult](https://github.com/lukhnos/lucenestudy/blob/f992866738da1d15c45db663c4ef3eb074adb65e/src/main/java/org/lukhnos/lucenestudy/SearchResult.java#L65) class in the submodule lucenestudy.
