### ISSUE TITLE
index failed on some 4.x devices

### ISSUE THREAD

**Issue by yangshulin2019** [lukhnos/LuceneSearchDemo-Android#4]
When I indexed tens of html files, I find that some 4.x device will fail to build the index. The error is in function writeTerm of PushPostingsWriterBase.java, the postingsEnum.nextDoc will return a docId exceed the size of docsSeen. You can run a Nexus 7, android 4.4 android studio emulator to get the bug. Other version is Ok.
I don't know what is the cause.

**Comment by lukhnos** [comment]
I no longer actively work on this project. [FixedBitSet](https://github.com/lukhnos/mobilelucene/blob/840320b2696c0850f073325ed15b6090d7a9760b/lucene/core/src/java/org/apache/lucene/util/FixedBitSet.java#L34) involves quite some "low-level" operations and I wouldn't be surprised if there are some edge cases on Nexus 7 + Android 4.4 (which is a fairly old Android version), perhaps it's a Dalvik thing or a device thing.

If you can reliable reproduce this problem, figuring out how PushPostingsWriterBase is using TermsEnum and FixedBitSet, and how they behave differently on functional and non-functional devices, may be the key to resolve your bug. Unfortunately I don't have any more insights that I can offer.
