### ISSUE TITLE
No results and crash on a release version 

### ISSUE THREAD

**Issue by rachidlaborantin** [lukhnos/LuceneSearchDemo-Android#6]
Thanks for the project
I used it in my android app 
When I test with a virtual device, it run correctly but when I enter a text and click search button, the query don't give a result and it toast this error 
"No segments* file found in NIO ... /index/index lock factory = Native Lock factory" 

The second problem is when I build a release version of my app and install it on a physical device, it crach when I click on search button 

I use lucene version 7... 

Hope you reply, thanks

**Comment by lukhnos** [comment]
I'm afraid that I don't have any ideas. This project is supposed to work only with Mobile Lucene, which is a heavily-modified version of Lucene 5, and I have stopped working on this project.

**Comment by rachidlaborantin** [comment]
I understand
I searched a mean to use the Lucene mobile but impossible 
No mean to import his project with dependencies, no jar file 
I don't found nothing 

Can you give me a Gradle dependencies or a jar file?

**Comment by lukhnos** [comment]
All the prebuilt JARs can be found here: https://github.com/lukhnos/lucenestudy/tree/mobile/libs ; it's in the `mobile` branch of the lucenestudy project.
